FROM cloudron/base:5.0.0@sha256:04fd70dbd8ad6149c19de39e35718e024417c3e01dc9c6637eaf4a41ec4e596c as base

RUN mkdir -p /app/code
WORKDIR /app/code

RUN export LANG=en_US.UTF-8
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8

# maybe check https://www.recoll.org/pages/features.html#doctypes.pdf also
RUN apt-get update && \
    apt-get install -y recollcmd recoll libwpd-tools poppler-utils unrtf untex wv pdftk antiword fonts-nanum libwpd-tools djvulibre-bin \
    python3-chardet python3-py7zr python3-chm python3-icalendar python3-lxml python3-mido python3-mutagen python3-rarfile && \
    rm -r /var/cache/apt /var/lib/apt/lists

# renovate: datasource=gitlab-tags depName=apps/cubby versioning=semver extractVersion=^v(?<version>.+)$ registryUrl=https://git.cloudron.io
ARG CUBBY_VERSION=2.7.1

RUN curl -L https://git.cloudron.io/apps/cubby/-/archive/v${CUBBY_VERSION}/cubby-v${CUBBY_VERSION}.tar.gz | tar -xz --strip-components 1 -f - -C .

# for development
# ARG DEV_BRANCH=main
# RUN curl -L https://git.cloudron.io/apps/cubby/-/archive/${DEV_BRANCH}/cubby-${DEV_BRANCH}.tar.gz | tar -xz --strip-components 1 -f - -C .

RUN npm install --no-update-notifier --no-audit --no-fund --omit dev

FROM base AS frontend

WORKDIR /app/code/frontend
RUN npm install --no-audit --no-fund --no-update-notifier
RUN npm run build
RUN ls -l

FROM base AS final

COPY --from=frontend /app/code/frontend-dist ./frontend-dist
COPY start.sh /app/code/

CMD [ "/app/code/start.sh" ]
